# Generated by Django 6.0.6 on 2026-06-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_care_gap', '0002_alter_caregap_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregap',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='caregap',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='caregap',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=1),
        ),
        migrations.AlterField(
            model_name='caregap',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('CONT', 'Contacted'), ('FUN', 'Follow-up Needed'), ('COM', 'Completed')], default='NS', max_length=5),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
