# Generated by Django 6.0.6 on 2026-06-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_care_gap', '0003_caregap_created_at_caregap_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregap',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
