# Generated by Django 6.0.6 on 2026-07-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_care_gap', '0004_alter_caregap_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregap',
            name='care_gap_type',
            field=models.CharField(choices=[('Annual Wellness Visit', 'Annual Wellness Visit'), ('Medication Check', 'Medication Check'), ('Screening Reminder', 'Screening Reminder'), ('Post-Discharge Follow-Up', 'Post-Discharge Follow-Up')], default='Annual Wellness Visit', max_length=30),
        ),
        migrations.AlterField(
            model_name='caregap',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=10),
        ),
        migrations.AlterField(
            model_name='caregap',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Contacted', 'Contacted'), ('Follow-up Needed', 'Follow-up Needed'), ('Completed', 'Completed')], default='Not Started', max_length=30),
        ),
    ]
