# Generated by Django 6.0.6 on 2026-06-25 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
                ('language', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CareGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_gap_type', models.CharField(choices=[('AWV', 'Annual Wellness Visit'), ('MC', 'Medication Check'), ('SR', 'Screening Reminder'), ('PDFU', 'Post-Discharge Follow-Up')], default='AWV', max_length=4)),
                ('priority', models.CharField(choices=[('L', 'l=Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=6)),
                ('status', models.CharField(choices=[('NS', 'Not Started'), ('CONT', 'Contacted'), ('FUN', 'Follow-up Needed'), ('COM', 'Completed')], default='NS', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_gaps', to='patient_care_gap.patient')),
            ],
        ),
    ]
