# Generated by Django 6.0.6 on 2026-06-25 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_care_gap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregap',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], default='L', max_length=6),
        ),
    ]
